{{- if .Values.harbor.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: secret-urunner
type: Opaque
stringData:
  URUNNER_SECR_HARBOR_USER: {{ .Values.harbor.username | quote }}
  URUNNER_SECR_HARBOR_PASS: {{ .Values.harbor.password | quote }}
{{- end }}

