{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "urunner.serviceAccountName" . }}
  labels:
    {{- include "urunner.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: sa-urunner
  namespace: urunner
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ include "urunner.clusterRoleName" . }}
  apiGroup: ""
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "urunner.clusterRoleName" . }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
{{- end }}
